### PR TITLE
Add support for ppc64le

### PR DESCRIPTION
**Pull request by rpsene**
Screen Shot 2019-09-09 at 20 20 06

### CODE REVIEW

**Comment by rpsene** [comment]
@fd0 could you take a look at this PR?

**Comment by Prajyot-Parab** [comment]
@fd0 are there any concerns that should be addressed here or we are good to merge this one?

**Comment by moritzdietz** [comment]
I know that he has limited time right now to merge PRs here and in restic/restic.
So for now please bear with him and manually apply this PR in your cloned repo.

**Comment by rpsene** [comment]
@moritzdietz thanks for let is know. We have an automation in place which builds the Power version and puts it at https://oplab9.parqtec.unicamp.br/pub/ppc64el/restic/beta/.

This is for the beta only, we will do the same for the restic releases.

**Review by mholt — APPROVED** [review]
I figure, if it compiles for this architecture, it's _probably_ fine, and if not, it can be fixed then.

**Comment by rpsene** [comment]
@mholt you are right as it is cross compiling for Power. Thanks again!

**Review by fd0 — APPROVED** [review]
LGTM, thank you very much (and I'm really sorry for the long time you had to wait for this one).

**Pull request merged**
